### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by brageskj** [InfectedLan/InfectedMain#12]
- [x] Smooth transition on navbar for responsive desktop <
- [x] Center content on onsite.php(.html)
- [x] "Buy ticket" button should be less tall (are you sure? @petterroea )
- [x] Remove the header with transparent background on info pages, we want to get "straight to the info with no scrolling down"
- [x] Investigate feasability of using same green color as infected tickets

**Comment by petterroea** [comment]
Warbo also had a few other tweaks that you need to collaborate with him on, but don't bother him until infected is well under way. He is busy AF

**Comment by exeron** [comment]
Is the color right? Changed to #21a80f (using hex instead of rgb.)

**Comment by halvors** [comment]
@brageskj @petterroea Seems like this TODO list is completed?

**Comment by petterroea** [comment]
yes
